apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    actions:
      1:
        action: {{.Values.action}}
        description: >-
{{ toYaml .Values.logstashDescription | indent 10 }}
        options:
{{ toYaml .Values.options | indent 10 }}
        filters:
{{ toYaml .Values.logstashFilters | indent 10 }}
      2:
        action: {{.Values.action}}
        description: >-
{{ toYaml .Values.logsystemdDescription | indent 10 }}
        options:
{{ toYaml .Values.options | indent 10 }}
        filters:
{{ toYaml .Values.logsystemdFilters | indent 10 }}


  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
{{ toYaml .Values.client | indent 6 }}
    logging:
{{ toYaml .Values.logging | indent 6 }}
