apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.name }}
            image: "{{ .Values.image }}"
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            env:
            - name: ES_USERPASS
              valueFrom:
                secretKeyRef:
                  key: userpass
                  name: {{ template "fullname" . }}-auth
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
            resources:
              limits:
                cpu: 50m
                memory: 200Mi
              requests:
                cpu: 50m
                memory: 200Mi
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
